# cargo

# [[file:~/Workspace/Programming/gchemol-rs/text-parser/text-parser.note::*cargo][cargo:1]]
[package]
name = "textparser"
version = "0.0.2"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "0.4"
nom = "4.1"

[dev-dependencies]
structopt = "*"
# cargo:1 ends here
