# cargo

# [[file:~/Workspace/Programming/gchemol-rs/parser/parser.note::*cargo][cargo:1]]
[package]
name = "text-parser"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
guts = { git = "https://github.com/ybyygu/guts.git" }
#guts = { path = "../../guts" }
nom = "5"

[dev-dependencies]
structopt = "0.3"

[features]
adhoc = []
# cargo:1 ends here
