# cargo

# [[file:~/Workspace/Programming/gchemol-rs/parser/parser.note::*cargo][cargo:1]]
[package]
name = "gchemol-parser"
version = "0.0.8"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "Text parsing made simple"
homepage = "https://github.com/gchemol/parser"
repository = "https://github.com/gchemol/parser"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
gchemol-gut = "0.0.8"
nom = "5"

[dev-dependencies]
structopt = "0.3"

[features]
adhoc = []
# cargo:1 ends here
